name: CI/CD Pipeline

on:
  push:
    branches:
      - main       # Trigger on push to main
      - develop    # Trigger on push to develop
      - controller/*  # Trigger on any feature branch
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.1'  # Specify your Go version

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build -o myapp .

      - name: Deploy
        run: echo "Deployment step here" # Placeholder for deployment command
